name: Webhook testing
on: [push]

jobs:
  testsuite-a:
    runs-on: ubuntu-latest
    steps:
      - name: Fail the test
        run: cp doesnt_exist /dev/null
      - name: Broadcast failure
        if: ${{ failure() }}
        uses: surgiollc/slack-action@v1
        with:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  testsuite-b:
    runs-on: ubuntu-latest
    steps:
      - name: Fail the test
        run: cp doesnt_exist /dev/null
      - name: Broadcast failure
        if: ${{ failure() }}
        uses: surgiollc/slack-action@v1
        with:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
