name: Webhook testing
on: [push]

jobs:
  testsuite-a:
    runs-on: ubuntu-latest
    steps:
      - name: Fail the test
        run: cp doesnt_exist /dev/null
      - name: Broadcast failure
        if: ${{ failure() }}
        uses: surgiollc/slack-action@testing
        with:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
